# Generated by Django 6.0.3 on 2026-08-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(choices=[(1, 'День 1'), (2, 'День 2'), (3, 'День 3'), (4, 'День 4'), (5, 'День 5'), (6, 'День 6'), (7, 'День 7'), (8, 'День 8'), (9, 'День 9'), (10, 'День 10')], unique=True, verbose_name='Номер дня в цикле')),
                ('image', models.ImageField(upload_to='menu/', verbose_name='Фото меню')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание (необязательно)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фото меню',
                'verbose_name_plural': 'Фото меню (10 дней)',
                'ordering': ['day_number'],
            },
        ),
    ]
